### ISSUE TITLE
Really bad accessibilty

### ISSUE THREAD

**Issue by andria-dev** [mucahitgurbuz/htm-editable-resume#1]
**Issue:**
 - Some buttons don't have text (didn't thoroughly check each one). If they don't have text they should have a `title` attribute that would have said text.
 - Inputs don't seem to have labels or placeholders, it is impossible to tell what's what.

The labels, if added, should describe what the input is for (i.e. _Name_, _Location_) and the placeholders should just be example values in the correct format.

**Comment by mucahitgurbuz** [comment]
Thanks for the feedback. I added placeholder to all inputs and title to all buttons.
The idea behind the form was the see exactly the same thing as exported pdf while you are editing. Therefore, placing labels are not good..
